name: Hexo Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Update Submodule
      run: |
        git submodule init
        git submodule update --remote

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install
      run: |
        npm config set registry https://registry.npmmirror.com/
        npm cache clean --force
        npm install -g hexo-cli --registry=https://registry.npmmirror.com/
        npm install --registry=https://registry.npmmirror.com/

    - name: Build
      run: |
        hexo clean
        hexo generate

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
